# Generated by Django 5.1.1 on 2024-09-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_medicalrecord_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
