# Generated by Django 5.1.1 on 2024-09-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appointment_notes_appointment_status_and_more'),
        ('accounts', '0003_alter_medicalrecord_report'),
    ]

    operations = [
    ]
